# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x14\n\x03row\x12\r\n\x05value\x18\x01 \x03(\x05\"\x1b\n\x06matrix\x12\x11\n\x03row\x18\x01 \x03(\x0b\x32\x04.row\"C\n\x0brequest_msg\x12\x19\n\x08matrix_1\x18\x01 \x01(\x0b\x32\x07.matrix\x12\x19\n\x08matrix_2\x18\x02 \x01(\x0b\x32\x07.matrix\"\'\n\x0cresponse_msg\x12\x17\n\x06result\x18\x01 \x01(\x0b\x32\x07.matrix2_\n\x03\x43\x61l\x12+\n\nadd_matrix\x12\x0c.request_msg\x1a\r.response_msg\"\x00\x12+\n\nmul_matrix\x12\x0c.request_msg\x1a\r.response_msg\"\x00\x62\x06proto3')



_ROW = DESCRIPTOR.message_types_by_name['row']
_MATRIX = DESCRIPTOR.message_types_by_name['matrix']
_REQUEST_MSG = DESCRIPTOR.message_types_by_name['request_msg']
_RESPONSE_MSG = DESCRIPTOR.message_types_by_name['response_msg']
row = _reflection.GeneratedProtocolMessageType('row', (_message.Message,), {
  'DESCRIPTOR' : _ROW,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:row)
  })
_sym_db.RegisterMessage(row)

matrix = _reflection.GeneratedProtocolMessageType('matrix', (_message.Message,), {
  'DESCRIPTOR' : _MATRIX,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:matrix)
  })
_sym_db.RegisterMessage(matrix)

request_msg = _reflection.GeneratedProtocolMessageType('request_msg', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST_MSG,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:request_msg)
  })
_sym_db.RegisterMessage(request_msg)

response_msg = _reflection.GeneratedProtocolMessageType('response_msg', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE_MSG,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:response_msg)
  })
_sym_db.RegisterMessage(response_msg)

_CAL = DESCRIPTOR.services_by_name['Cal']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROW._serialized_start=17
  _ROW._serialized_end=37
  _MATRIX._serialized_start=39
  _MATRIX._serialized_end=66
  _REQUEST_MSG._serialized_start=68
  _REQUEST_MSG._serialized_end=135
  _RESPONSE_MSG._serialized_start=137
  _RESPONSE_MSG._serialized_end=176
  _CAL._serialized_start=178
  _CAL._serialized_end=273
# @@protoc_insertion_point(module_scope)
